### ISSUE TITLE
in console.py destroy returning error

### ISSUE THREAD

**Issue by haddyadnan** [haddyadnan/AirBnB_clone#24]
Traceback (most recent call last):
  File "./console.py", line 209, in <module>
    HBNBCommand().cmdloop()
  File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "./console.py", line 134, in do_destroy
    self.__relaod()
AttributeError: 'HBNBCommand' object has no attribute '_HBNBCommand__relaod'

**Comment by haddyadnan** [comment]
fixed
